version: '3.6'
services:
  redis:
    image: redis:6.0.9-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
  bot:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    restart: unless-stopped
