version: '3.6'
services:
  redis:
    image: redis:6.0.9-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
  bot:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    restart: unless-stopped
    depends_on:
      - redis
